Name:     "Bio-Server"
Version:  "a2.0.1"
Server:
  ServerPort:     3000
  ServerIp:       "localhost"
  ServerAddress:  ":3000"
  ServerConfig:
    ReadTimeout:      "5s"
    WriteTimeout:     "5s"
    ShutdownTimeout:  "5s"
